const express = require("express");
const adminAuthRoutes = require("./adminAuthRoutes");
const adminDashboardRoutes = require("./adminDashboardRoutes");
const adminUserRoutes = require("./adminUserRoutes");
const adminRecruiterRoutes = require("./adminRecruiterRoutes");
const adminJobRoutes = require("./adminJobRoutes");
const adminApplicationRoutes = require("./adminApplicationRoutes");
const adminAnnouncementRoutes = require("./adminAnnouncementRoutes");
const adminActivityRoutes = require("./adminActivityRoutes");
const adminSettingsRoutes = require("./adminSettingsRoutes");
const adminAssessmentRoutes = require("./adminAssessmentRoutes");
const adminSearchRoutes = require("./adminSearchRoutes");
const router = express.Router();
router.use("/auth", adminAuthRoutes);
router.use("/dashboard", adminDashboardRoutes);
router.use("/users", adminUserRoutes);
router.use("/recruiters", adminRecruiterRoutes);
router.use("/jobs", adminJobRoutes);
router.use("/applications", adminApplicationRoutes);
router.use("/announcements", adminAnnouncementRoutes);
router.use("/notifications", adminActivityRoutes);
router.use("/settings", adminSettingsRoutes);
router.use("/assessments", adminAssessmentRoutes);
router.use("/search", adminSearchRoutes);
module.exports = router;
