const express = require("express");
const {scheduleInterviewHandler,listInterviewsHandler,listMyInterviewsHandler,rescheduleInterviewHandler,updateInterviewStatusHandler} = require("../controllers/interviewController");
const { protect, authorizeRoles } = require("../middleware/authMiddleware");
const router = express.Router();
router.post("/", protect, authorizeRoles("recruiter"), scheduleInterviewHandler);
router.get("/", protect, authorizeRoles("recruiter"), listInterviewsHandler);
router.get("/my", protect, authorizeRoles("jobseeker"), listMyInterviewsHandler);
router.patch("/:id", protect, authorizeRoles("recruiter"), rescheduleInterviewHandler);
router.patch("/:id/status", protect, authorizeRoles("recruiter"), updateInterviewStatusHandler);
module.exports = router;
